version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /src/backends/azure-api/PowerAndAzureAsCode.Api
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /src/backends/dataverse/PowerAndAzureAsCode.Dataverse.Plugins
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
